name: Tests

on:
  pull_request:
    branches: ["main"]
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get ./...
      - name: Coverage
        run: bash testcase/integrationtest.sh
      - name: Test
        run: go test ./testcase/...
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: testcase/covdatafiles/profile.cov
